### ISSUE TITLE
[Feature Request] Allow browsing widget content

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.aura#1]
Is there any way you could add a way to browse "into" the content shown by a widget? That way, even if we have a limit on how many items are shown, we still have a way to see all the content.

**Comment by jurialmunkey** [comment]
Not currently, but I have something planned for this in the Leia version which will use some of the new features of the skinning engine.

**Comment by drinfernoo** [comment]
Sounds good! I haven't tried out Leia yet, but it looks like I may be migrating soon.

**Comment by jurialmunkey** [comment]
Latest commit on Leia branch adds this feature.
https://github.com/jurialmunkey/skin.aura/commit/3c1dfd8ccea16869decf8ad6b444a8299ff25fcd

**Comment by drinfernoo** [comment]
Awesome! I just updated earlier before that commit, though :P

**Comment by drinfernoo** [comment]
Is there any way we might be getting this feature on Krypton?
