### ISSUE TITLE
PVR OSD progress bar

### ISSUE THREAD

**Issue by loggio** [jurialmunkey/skin.aura#10]
The progress bar in fullscreen livetv is constantly jumping back and forth. Compare this to estuary where the bar works as it should and stays constant with the progress.

**Comment by jurialmunkey** [comment]
Is this on Leia? Did this only start happening recently?

**Comment by loggio** [comment]
Yes..sorry, it's leia.

It has probably always been this way but I never really picked up on it.

On 26 May 2018, at 4:41 pm, jurialmunkey <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this on Leia? Did this only start happening recently?

**Comment by loggio** [comment]
G'day,

Had some spare time today to take a look at this, i've fixed this issue. See attachment.

Issue was with missing info's and labels PVR.EpgEventProgess,  PVR.EpgEventElapsedTime & PVR.EpgEventDuration

added new conditional "progress id=499" for livetv 
added visibility condition to "progess" control
added PVR.EpgEventElapsedTime label
added PVR.EpgEventDuration label

[Includes_Statusbar.zip](https://github.com/jurialmunkey/skin.aura/files/2065592/Includes_Statusbar.zip)

**Comment by jurialmunkey** [comment]
Excellent, thanks.

Why do you hide the cache bar for livetv? Isn't this used when rewinding / pausing livetv?

**Comment by jurialmunkey** [comment]
Also, can you please test latest commit and confirm that everything is working correctly.

**Comment by loggio** [comment]
It's better, but when timeshifting (seeking) id=401 jumps all over the place. 

I've commented out "progess id=401"  and changed it to a slider and added a separate slider for pvr id=402... This seems to be how Estuary handles it. Working fine for me using this approach...
Have a look, you might want to change the textures though i just took a guess with them in order to prove this would work.

[Includes_Statusbar.zip](https://github.com/jurialmunkey/skin.aura/files/2065824/Includes_Statusbar.zip)

**Comment by loggio** [comment]
Also, you need to change
label_OSD_duration 
from
!String.IsEmpty(PVR.EpgEventElapsedDuration) & $INFO[PVR.EpgEventElapsedDuration
to
!String.IsEmpty(PVR.EpgEventDuration) & $INFO[PVR.EpgEventDuration]

**Comment by jurialmunkey** [comment]
Ah yeah you are right about 402, not sure when that change happened. Updated on latest git. Also fixed the duration mistake (thanks for catching that). 

Thanks for your help! :grin:

**Comment by loggio** [comment]
No worries at all
And sorry about my hacky attempts at coding by the way, I know it's probably frustrating for you to have to sort my mess out... i wish I had your smarts in that department. I'm just squeezed to find the time to be able to clean and polish.
