### ISSUE TITLE
Dolby Atmos/DTS-X logo support

### ISSUE THREAD

**Issue by gsantosoliver** [jurialmunkey/skin.aura#12]
# User Story
As I user I would like to choose to whether or not use portions of filenames to display media information such as Dolby Atmos and DTS-X

## Details
@jurialmunkey explained in the thread: https://forum.kodi.tv/showthread.php?tid=328558&pid=2741727#pid2741727

> DTS-X and Atmos media flags are not supported by Kodi because of a limitation in ffmpeg. Kodi can't decode Atmos and DTS-X natively - those codecs only work via bitstream passthrough. Any skin that shows these flags is just faking it by using part of the filename to determine whether to show it or not. For me personally, I think filename checks should only be used for information about the source (e.g. whether it came from a bluray, dvd, or webrip for example), and not for information about how it is encoded. 

The DTS-X movies display the "DTS-HD MA" logo whereas the Dolby Atmos ones display the "Dolby True HD" logo. Here are some screnshoots: 
![kodi_20180607_231346](https://user-images.githubusercontent.com/31668431/41234916-e2626f68-6d63-11e8-844b-243b4d5b8400.png)
![kodi_20180607_231254](https://user-images.githubusercontent.com/31668431/41234917-e28a3976-6d63-11e8-9928-84b7558afb70.png)

System used:
- NVIDIA Shield
- Android 8
- Kodi 17.6 Krypton

## Solution Proposal
The idea is to let the user chooses if he wants to use filenames to trigger the DTS-X and Dolby Atmos logos or not. In case the user chooses so, the movie files (or folder where they are) which have the subtrings "atmos" or "dts-x", "dtsx", "dts x", "dts:x" should display the Atmos or DTS-X logo respectively along with the other media information already available.

**Comment by jurialmunkey** [comment]
What purpose does the filename override serve?  Kodi can't decode Atmos files as Atmos - instead it decodes to LPCM from the True HD stream, so TrueHD is the codec being used. Overriding this with a filename flag is essentially misreporting the actual codec in use - why would you want to do this?

BTW- I am open to adding this option, but I need to understand the rationale and use-case for it first.

**Comment by gsantosoliver** [comment]
@jurialmunkey: I understood the Kodi limitation the first time you explained. The idea is that the user can control when to enable this feature instead of implementing it as default. In other words, give the control to the user on whether or not he wants to use it. You may include a warning when it is activated explaining the Kodi limitation. :)

User case: I have a HUGE 4k movie collection which some of them are Dolby Atmos or DTS-X. All these movies include substrings to identify them as Dolby Atmos or DTS-X in there filenames and folders. I can easily identify them when using the "Files" interface - which is almost like the Windows Explorer or Finder. Since I am setting a new system I would like to use a more user-friendly interface than "Files", the idea is to use the "Movies" interface. Currently there is no way to say whether or not a movie has Dolby Atmos or DTS-X in the "Movies" interface. So, as an user, I would like to be able to identify the Dolby Atmos and DTS-X content when using the "Movies" interface.

I see this is a kind of an expert feature, people using this feature will know what they are doing and it will not harm Kodi users that do not use it.

**Comment by jurialmunkey** [comment]
Yes, but why is it important for you to identify if something is Atmos / DTS-X content? What purpose does having that information serve? 

There is way too much option bloat in this skin already - having an option for every little preference makes the settings difficult to navigate and confusing for new users. For something like this I am either going to implement it as default because the reasoning behind it makes sense, or not at all.

For me to implement this feature, I need to know why it is important for you to identify Atmos content beyond just that you think it would look cool. Kodi is only going to use the TrueHD stream, so why do you need to identify Atmos?

**Comment by gsantosoliver** [comment]
@jurialmunkey - it is fear enough. 

Let me expand a little bit more on the use case. We've built a brand new Dolby Atmos room here which are going to be used by people of different levels of skill set, o using the Movies interface to navigate through the movies is required. I would like them to be able to pick content that will use most of what the home theater room can offer (Dolby Atmos/DTS-X/HDR) when they are looking at the "Movies" library available (it is huge, 300+ movies). It will help tremendously to know weather or not the selected movie has object based audio, since "Dolby TRUEHD" may or may not be Atmos - same for "DTS HD-MA" which may or may not be DTS-X. We are using the audio passthrough so that the Denon receiver can do all the audio decoding work so it is important to us to know before playing the movie what type of audio we are going to get. The only way we can differentiate the audio for certain is when we play the movie and show the codec information in the receiver. 

This would be just one extra switch option in the settings (expert) that would not be enabled by default so that you can guarantee what only those who know what they are doing use it. :)    

I hope it makes sense and thank you so much for your attention on this one.

**Comment by jurialmunkey** [comment]
Okay, yes that use case makes sense. Thanks for explaining, as it is important for me to be able to think about the best approach to the issue. As I stated before, I dont want to add another option, so this will simply be built in by default.

Im wondering if a better approach might be to show the atmos/dts-x flag as an additional flag (similar to how the HDR flag works). That way you can see both what codec kodi will use, and that the file is flagged as being atmos compatible for passthrough audio. Would that be a suitable solution?

**Comment by gsantosoliver** [comment]
@jurialmunkey - thank you so much to agree on moving forward with this user story! And yes, adding this as an additional flag will work just fine! ;)

**Comment by jurialmunkey** [comment]
Can you test latest commit and confirm that everything is working correctly. 
I've added checks for atmos, dts-x, dtsx, dts:x, dts x

**Comment by jurialmunkey** [comment]
Ok. Yeah, I was a bit iffy about including "dts x" for that exact reason. I've removed it now. 
Checks are now "dts-x" "dts:x" and "dtsx".
