### ISSUE TITLE
Problems to change audio track when using a restricted profile

### ISSUE THREAD

**Issue by gsantosoliver** [jurialmunkey/skin.aura#13]
## Problem
There is a black text in the location where the audio menu was supposed to be when accessing the movies settings during the playback.

## Steps to reproduce
1. Create a profile in KODI without any type of privilegies other than accessing the videos
2. Play a movie with more than one sound track
3. Bring the menu and click on the settings icon
4. The Audio setup is blank - the "Audio setup" text does not appear where it should be.
![img_20180619_181042](https://user-images.githubusercontent.com/31668431/41667007-42af3e08-7482-11e8-8556-16658d789dc1.jpg)

**Comment by jurialmunkey** [comment]
Unfortunately, this is a long standing Kodi bug, so not much I can do about it. Basically, when switching profiles, kodi fails to load some of the strings defined by the skin.

As a work around, you should be able to fix it by doing a ReloadSkin() after loading the profile. Reload skin is in the shutdown menu by default ("S" on keyboard).

**Comment by gsantosoliver** [comment]
Oh, I did not know! Thanks for the workaround!
