### ISSUE TITLE
ExtendedInfo support for TV Shows

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.aura#19]
/u/OpenELEQ highlighted [this point](https://reddit.com/r/Addons4Kodi/comments/97ynkm/cannot_get_wraith_to_open_for_tv_shows/e4d3clx?context=3), where I had always assumed it was an EIS issue. Is it possible that this implementation is missing in Aura?

**Comment by SerpentDrago** [comment]
I can Confirm , EIS  , works fine from widget for anything but tvshows. No matter the addon / etc etc .

**Comment by SerpentDrago** [comment]
meta.update({'tvshowtitle': systitle})

Line seems to fix this in addons . for future notice
