### ISSUE TITLE
Scrollbars are missing - Leia

### ISSUE THREAD

**Issue by loggio** [jurialmunkey/skin.aura#2]
Hi, 

As the tittle suggests, the scrollbars are missing in Leia. 
I came across this issue when converting you AZ skin to Leia, something to do with id="60" I think.
I found changing the id to something else would fix the scroll bar for some views, but break it for others.... Really weird.

**Comment by jurialmunkey** [comment]
Yeah Leia does some weird stuff with scrollbars.

Which ones are missing / not working?

**Comment by loggio** [comment]
All of them as far as I can tell. The only place I see them are in file browser dialogs.

**Comment by jurialmunkey** [comment]
Scrollbars are working fine for me on Leia in all the library views.

**Comment by loggio** [comment]
Ok that's incredibly strange. What platform are you running? I've got android (nvidia shield) and 4 Pi's running Libreelec and none of them are displaying the scroll bars. 

As soon as I installed krypton on my laptop, and the krypton version of aura they work fine.

**Comment by jurialmunkey** [comment]
I'm using Fedora (Linux). Compiled from source.

Are the scrollbars not there? Or can't navigate to them? Or displaying incorrectly?

Can you maybe grab a screenshot.

**Comment by loggio** [comment]
I can navigate to them and use them... I just can't see them, they're invisible. I can take a screenshot... But there's nothing to see

**Comment by jurialmunkey** [comment]
I wonder if maybe your screen calibration or resolution is set incorrectly? 
They look and work completely fine for me in Leia:
Unfocused - https://i.imgur.com/dligHPf.jpg 
Focused - https://i.imgur.com/jBPyEN9.jpg

**Comment by loggio** [comment]
I thought that... But it's not the case. Like I said, same thing was happening with AZ until I fiddled with the Id. I have 5 media center setups, all on different TV's... One on a projector. None show the scroll bar. 

Switch to estuary and scroll bars work fine. 

Weird as.

**Comment by loggio** [comment]
Wait stop.... my bad. Your right. I totally forgot that I calibrate the screen a little wider than default as I use to see white lines in the top left of some pvr shows this would eliminate that effect. 

Weird though, all my Tvs must slightly over scan as I've had to bring the blue lines of the screen calibration in slightly further than I normally would. 

Man I feel dumb as. Sorry to bother you haha. Happy Easter.

**Comment by jurialmunkey** [comment]
Haha. No worries, glad we sorted it out in the end. 

Instead of screen calibration, you should use "Zoom Amount" in the video settings to get a little bit of overscan on the video only:
https://i.imgur.com/yCEbqYf.png
