### ISSUE TITLE
More of a feature request, but...

### ISSUE THREAD

**Issue by pencey** [jurialmunkey/skin.aura#20]
Is there any way to get Rotten Tomato or IMDB ratings when browsing? Would be super cool to add them to widgets on home page.

**Comment by drinfernoo** [comment]
In the `script.module.metadatautils` settings, you can add an OMDb API key, which will put ratings on the skin's views, as explained in the release post on the Kodi forum.

**Comment by pencey** [comment]
Thank you!

**Comment by zzzdeb** [comment]
@drinfernoo Were you able to achieve what you want? I could not show the rating. What I want to see is something like this (In picture, rating is shown in bottom corner).

![pic-window-200213-1717-24](https://user-images.githubusercontent.com/22198738/74455076-1a795e80-4e85-11ea-97ec-47c76642ad09.png)

I changed some file to achieve this. @pencey do you think it is already implemented? In that case, can you please show some visual instruction or at least end result? Would be great.

**Comment by drinfernoo** [comment]
Oh, no... they won't show up on the homescreen.

**Comment by zzzdeb** [comment]
Alright. What do you think of this feature. Estuary(default skin) offers it and I really like it. I would love to contribute. What do you think?
