### ISSUE TITLE
[Bug] - Repeat option not available in VideoOSD

### ISSUE THREAD

**Issue by aenima99x** [jurialmunkey/skin.aura#24]
In the Video OSD, the repeat togglebutton is not available. It does show in the Music OSD.
In the Includes_OSD.xml, the repeat toglebuttons (ID's 20, 21 & 22) have the the visibilty set to only the MusicOSD with  <visible>Window.IsVisible(musicosd)</visible>
Removing that visible tag makes the repeat buttn visible in the VideoOSD

**Comment by jurialmunkey** [comment]
It's not in Estuary either. 

I think it adds unnecessary clutter as setting videos to repeat is not a common use case. Main place you would use it is in a playlist or the now playing queue, and it is possible to set repeat on/off from the top menu in playlist/queue.
