### ISSUE TITLE
[Feature Request] - Option to display Logo if available

### ISSUE THREAD

**Issue by aenima99x** [jurialmunkey/skin.aura#25]
Would like the ability to show logos in the movie/tvshows/music libraries. If available the logo would be shown instead of the text title, but if not, then it falls back to the text title. Another option would be to possibly add the logo to the ight of the ratings/plot/etc

**Comment by jurialmunkey** [comment]
Unfortunately, clearlogos don't have consistent enough margins to make them align properly in place of the text titles.

The clearlogo will overlay the fanart in views that shows fanart (e.g. Episode List or Landscape Showcase)
