### ISSUE TITLE
[Feature Request] Selecting category widget changes widget display

### ISSUE THREAD

**Issue by Iruberiam** [jurialmunkey/skin.aura#36]
It would be amazing if the widget display beneath a main menu item could be dynamic. 
Is it possible to assign a widget to a category so that the widget display changes when the category is selected but NOT opened? For example, say Movies for an addon is selected, the widget displays all the movie widgets. If TV shows is then selected, the widget displays all the widgets pre assigned for TV shows.

I suppose what I'm asking is, is it possible for the categories to behave the same as the main menu items?

**Comment by drinfernoo** [comment]
I believe what you're talking about are hubs? @jurialmunkey has expressed interest in adding something like that, I believe.

**Comment by Iruberiam** [comment]
That's awesome! I heard about hubs but wasn't sure of what was meant by them. Thanks for your reply.

**Comment by Iruberiam** [comment]
Thanks for the explanation, Hubs sound like they perform a similar task so
I look forward to their arrival. The skin is great and performs well as it
is, I'm excited to see where this goes.
