### ISSUE TITLE
Wrong icon.jpg

### ISSUE THREAD

**Issue by RagnarLothbrok-Odin** [jurialmunkey/skin.aura#39]
Not a massive issue, but the icon.png for the Leia branch says Krypton

**Comment by drinfernoo** [comment]
Why don't you make a PR?

**Comment by RagnarLothbrok-Odin** [comment]
because I am a github noob, sorry Dad

**Comment by Sunseng** [comment]
You two really son and dad? Wahaha 🤣

**Comment by RagnarLothbrok-Odin** [comment]
No lmao

**Comment by RagnarLothbrok-Odin** [comment]
A noob closed the issue :(

**Comment by drinfernoo** [comment]
If you're not part of the solution, you're part of the pollution 🤣

**Comment by jurialmunkey** [comment]
Whoops! Thanks for reporting that - I would have never noticed!

Fixed on latest. I'll close this issue now 😉
