### ISSUE TITLE
Leia install problem

### ISSUE THREAD

**Issue by SavaRak** [jurialmunkey/skin.aura#43]
I have installed Leia today on Firestick. When click install from zip in kodi I get the message: "failed to install addon from zip file - the dependency on xbmc.gui version 5. 12.0 could not b..." can't read further cause the text disappears.

**Comment by drinfernoo** [comment]
You installed from the `master` branch. You need to download the zip of the `Leia` branch.

**Comment by SavaRak** [comment]
Did fix the problem. Thanks.
