### ISSUE TITLE
[Feature Request]  Favorites widget - display favorites without having to click anything

### ISSUE THREAD

**Issue by Xmetalfanx** [jurialmunkey/skin.aura#45]
not sure if i am missing something, but my idea is to show the favorites (like in say Esturay) as a widget or something like that if you have "favorites" in the main menu .. now you have to click favorites in the menu and then all the favorites come up ... playing with the skin for awhile I am thinking maybe a "favorites node" i think it is called ... or just whatever where you can have what shows when you click "favorites" in the menu, always appearing when you "highlight" favorites in the menu.

**Comment by notoco** [comment]
Install script.helper.widgets from Settings-skin settings-menage dependencies.
Go to home-customize home menu - select widget and go to additional widgets-skin helper service widgets - favorites - favorites.
