### ISSUE TITLE
clock on OSD

### ISSUE THREAD

**Issue by racuna** [jurialmunkey/skin.aura#46]
How can I show the current time on the OSD. Is very useful to not being too late binge-watching tv series.

**Comment by drinfernoo** [comment]
I'd really like the "Ends at X:xx" like a lot of skins have.

**Comment by jurialmunkey** [comment]
Press "info" on your remote or "i" on keyboard.

**Comment by drinfernoo** [comment]
@jurialmunkey Unfortunately, that only works for remotes with extra buttons or PC users... Most Android box users are up a creek on that one without buying a different remote.
