### ISSUE TITLE
Extended info slow to pop up

### ISSUE THREAD

**Issue by dylotribal** [jurialmunkey/skin.aura#47]
When you click 'Information' in the context menu it's very slow to pop up when Extended info is forced in the skin options.

**Comment by drinfernoo** [comment]
That's because ExtendedInfo Script is slow.

**Comment by dylotribal** [comment]
Thanks @drinfernoo .  When you click it, the interface appears to glitch.  It will do the transition but then suddenly is back to the same screen and then you wait 20 to sometimes 40 seconds for the popup to come up which is beyond the reward (I'll just pop up IMDB on my phone).  If I disable extendedinfo then trailers don't work in from the context menu as it's an open bug in Leia right now.  Maybe none of this has to do with the screen just looking for a way to view trailers from the context menu in Leia :)

**Comment by xbmcnut** [comment]
Mine takes about 7~8s which is worth the wait but if would be awesome if we could have the addition of a spinning indicator to let the wife know something is happening. :)

**Comment by dylotribal** [comment]
@xbmcnut ha same!  If it's waiting on API calls to finish it should at least bring up the next panel and as the asynch calls complete fill in the other info.  It's a great plugin other than this issue

**Comment by drinfernoo** [comment]
It's simply because EIS takes a long time to pull up, especially in Leia. There are some SHS errors that usually happen as well, since neither add-on has really been updated to work with Leia.

**Comment by jurialmunkey** [comment]
These are issues with extended info - nothing to do with the skin. It's up to the script to call the busy indicator.

**Comment by dylotribal** [comment]
Thanks @jurialmunkey.  Prob not the place to ask but does anyone know something that will play a trailer straight from the context menu.  I found 'play trailer's but it doesn't show up in Exodus etc only i think your own library.  Been looking everywhere.
