### ISSUE TITLE
Reorganize widgets

### ISSUE THREAD

**Issue by profucius** [jurialmunkey/skin.aura#49]
Is it possible to reorganize the widgets once you have created them? It seems they are hard set once you create them, sometimes I wish to create them as the inspiration comes to me, then move them around afterwards.

I found the skin.aura.properties file that seems to store the widgets, I found a way to hack it to, say, swap "Widget3" and "Widget4" in Notepad++, then load Kodi, reload skin, and it did work.

Any plans to make this possible from within Kodi directly?

**Comment by jurialmunkey** [comment]
Not possible to do from inside Kodi without editing the skinshortcuts addon or completely rewriting how the widgets are handled.
