### ISSUE TITLE
Overlap in PVR window

### ISSUE THREAD

**Issue by loggio** [jurialmunkey/skin.aura#5]
Hi jurialmunkey,

This is still happening in the PVR view. I have not modified anything. It's happening randomly but regularly when scrolling the list.
![kodi_20180405_061559](https://user-images.githubusercontent.com/16231443/38391880-fcc7bd38-3968-11e8-9ba1-ba6a13141544.png)

This video shows that the plot changes size every time, but the title does not.
https://youtu.be/6pnOdoUPokk

**Comment by loggio** [comment]
The info that is overlapping the fanart is suppose to be the "episode" title I think... 
But almost all Aussie OTA TV channels send their EPG data in a funny way. The episode title is often missing, or simply is exactly the same as the plot... Which results in these really long "episode titles" or episode titles that are exactly the same as the TV show title. which sucks, because this cannot be edited/changed in any way using TVHeadend. Channel 9 and all the other channels owned by 9 (GEM, 9Life etc...) seem to show the info correctly.

**Comment by jurialmunkey** [comment]
Yeah. The part after the hyphen is ListItem.EpisodeName, so that is being filled incorrectly.
However, it is unusual that the plot is not also overlapping. Can you try latest git and see if the issue persists?

**Comment by loggio** [comment]
Looks fixed to me. Will let you know if it happens again but I think it's all good now. 

Cheers

**Comment by jurialmunkey** [comment]
@loggio - Can you test latest commit and confirm that PVR artwork is working correctly? I've made some changes which hopefully will fix a few things, but I'm testing it blind as I'm just using demo PVR add-on.

**Comment by loggio** [comment]
Hey mate, yeah it seems fixed to me. I haven't been able to reproduce.

**Comment by jurialmunkey** [comment]
Excellent! Let me know if any issues arise.
