### ISSUE TITLE
Submenu/Categories widgets icons ratio

### ISSUE THREAD

**Issue by cwagner22** [jurialmunkey/skin.aura#51]
I have a display issue since I upgraded to Leia:
![screen shot 2019-02-19 at 15 07 11](https://user-images.githubusercontent.com/5314435/52999390-3277f700-3458-11e9-9258-d19517d8cae9.png)

As you can see the Submenu/Categories widgets don't keep the icons ratio.

**Comment by jurialmunkey** [comment]
Either put the icons in skin.aura/extras/icons folder or disable categories widget text. The skin assumes that if you choose an icon that isn't in the icons folder, then you want to stretch it to fill the box.

**Comment by cwagner22** [comment]
If I disable categories widget text the icons are still slightly stretched the opposite way since the box isn't a square. Any chance to have it work the same as the Krypton version?

**Comment by jurialmunkey** [comment]
With text disabled the box is square. If it's not square, then it's an issue with your resolution/screen not being 16:9.

**Comment by drinfernoo** [comment]
Why would the skin assume that icons outside of the icons folder should be stretched? That seems like a stretch (ha) for me.

**Comment by cwagner22** [comment]
Yeah, this is how it looks on my macbook pro:
![image](https://user-images.githubusercontent.com/5314435/53478968-9f1f7100-3aaa-11e9-9505-f6b8d1b105be.png)

On my tv it's better but not totally square, due to the resolution I suppose.
