### ISSUE TITLE
Widget sorting values inconsistent

### ISSUE THREAD

**Issue by bluenote73** [jurialmunkey/skin.aura#57]
Hi

Whenever I try to fill in the "sort" field value for widgets, I get weird behavior. Some values like "year" seem to work - the field shows updated, setting takes effect. But most values just get ignored and the edit widget display does not update the value displayed. Even trying to clear the value doesn't seem to work. Hopefully you can see what I mean easily. Thanks for aura, it's really good.

**Comment by bluenote73** [comment]
With a little more experimenting, I found out that I can nudge aura into taking into account the setting by editing the widget definition to pick the add-on again, I hope that helps.

**Comment by jurialmunkey** [comment]
This is a skin helper issue. Not much I can do about it.
