### ISSUE TITLE
(Request) Watched indicators in widget

### ISSUE THREAD

**Issue by Baardmans** [jurialmunkey/skin.aura#58]
Would be great to either have watched indicators on the main screen widgets or to be able to hide watched items. That way you can easily see if there are any unmatched episodes available for your favorite TV shows.

**Comment by drinfernoo** [comment]
This is already a thing.

**Comment by Baardmans** [comment]
@drinfernoo, you mean it should already be functioning? Because it doesn't for me... Or has it already been requested?

**Comment by pencey** [comment]
This is definitely already implemented. https://ibb.co/xMbPvF3

**Comment by Baardmans** [comment]
Thanks for the reply, but can someone explain why it isn't working on my setup?

**Comment by pencey** [comment]
Are you using trakt? That's what I'm using and it syncs trakt watched info to widget indicators. Other than that look through settings and make sure you have enable watched indicators

**Comment by Baardmans** [comment]
I use trakt, have my account synchronized with Exodus Redux and the Kodi Trakt app. I get watched indicators in my lists in Exodus Redux itself, just not on the main screen widgets...

**Comment by drinfernoo** [comment]
@Baardmans Third party add-ons have to do certain things on their side to allow for this. Try opening an issue with them.

**Comment by Baardmans** [comment]
@drinfernoo, thanks for the advice, will do that!

**Comment by Baardmans** [comment]
@pencey, I've been using Seren for a couple of days now (because I saw you were using that for your widget), but I still don't get any watched indicators... Again, in season and episode view is all working, just not on the widgets...

@jurialmunkey, could it be a missing dependency or something?

**Comment by prateek33** [comment]
I have the same problem with widgets from all the addons. None of the movies show the watched indicator on the homescreen.
@jurialmunkey any advices?
