### ISSUE TITLE
[Feature Request] Display entered time when jumping using keypad

### ISSUE THREAD

**Issue by xbmcnut** [jurialmunkey/skin.aura#61]
Would it be possible to have the time display on-screen when selecting to jump directly to a position in a show/movie? Entering _2000 > enter_ goes to 20:00 minutes into the show/movie but nothing is displayed so WAF not very good. :)

**Comment by jurialmunkey** [comment]
Should be fixed on latest git master now. Please confirm that it works correctly.

**Comment by xbmcnut** [comment]
Working perfectly in 1.0.5. Thank you so much. Wife very happy :)
