### ISSUE TITLE
Possible typo in message context number (msgctxt) for (Movie) Sets.

### ISSUE THREAD

**Issue by Lisa-Williams** [jurialmunkey/skin.aura#62]
Reference : [https://github.com/jurialmunkey/skin.aura/blob/master/1080i/script-script.extendedinfo-DialogVideoInfo.xml#L157-L175](https://github.com/jurialmunkey/skin.aura/blob/master/1080i/script-script.extendedinfo-DialogVideoInfo.xml#L157-L175)

In the above linked XML, both lists have a label defined as : ```<param name="label" value="$LOCALIZE[31206]" />```.
According to the comments in the XML, one list is for ```Similar```, the other for ```Sets```. But both ```strings.po``` files have context 31**_206_** defined as ```Similar```. I do notice that context 31**_260_** is defined as ```Movie Sets``` in both strings.po files. Is defining context 31206 twice, done deliberately or a typo?

**Comment by jurialmunkey** [comment]
Fixed! Thanks for the bug report 😄
