### ISSUE TITLE
Artist Slideshow update alert

### ISSUE THREAD

**Issue by boucchar** [jurialmunkey/skin.aura#83]
You are recently updated Artist Slideshow and the skin you are using does not support the New Slideshow display method...

Thats is the message i have when i listen music on aura.

**Comment by draconis244** [comment]
Same here, running Kodi 18.5 on Libreelec on Aura skin (taken from github), it briefly flashes up with the alert then it goes away once the artwork has been downloaded, can't see any way to stop it happening, each time the artist changes up it flashes ....very annoying

**Comment by alexbelgium** [comment]
Hi, I've created a pull request to solve the issue. Meanwhile you can do it manually by following the instructions here : https://forum.kodi.tv/showthread.php?tid=328558&pid=2918140#pid2918140

**Comment by boucchar** [comment]
> Hi, I've created a pull request to solve the issue. Meanwhile you can do it manually by following the instructions here : https://forum.kodi.tv/showthread.php?tid=328558&pid=2918140#pid2918140

Thank you very much! In fact, ive simply re download the 1.0.5 version and update via zip file in kodi, issue resolved!

**Comment by boucchar** [comment]
View previous comments for the fix
