### ISSUE TITLE
[question] kodi "matrix" 19 support?

### ISSUE THREAD

**Issue by LN13uLL** [jurialmunkey/skin.aura#94]
will the aura skin be worked on so it works in kodi 19?  sorry if this has been asked before.  it's my typical go-to skin currently for kodi 18.

**Comment by jurialmunkey** [comment]
Unlikely. I haven't touched this skin in a long time. I'm sure that someone will do a Matrix mod though.

**Comment by LN13uLL** [comment]
Gotcha.  That's understandable.  That's what I thought, but just wanted to hear it directly.
