### ISSUE TITLE
[Feature request] Favorites widget

### ISSUE THREAD

**Issue by freijon** [jurialmunkey/skin.aura#95]
Hello,

I added a "Favorites" tab to my home screen, but unfortunately this tab is empty until I click, only then will it display the Favorites-Menu. It would be nice to have a Widget which displays all favorites. Maybe this is already possible with a customized entry but I'm not skilled enough to know what to fill out ;)

**Comment by harryirvine** [comment]
Hey there, 
It auto loads the full favs widget for me. 

Here's what I did: Go to customise main menu in settings and select the tab you want to create the widget under. Create a new widget and then select: Additional Widgets > Skin Helper Service Widgets > Favourites > Favourites

Put in a name and you should be good to go.

**Comment by freijon** [comment]
I don't have this option. Under Additional Widgets I only have "Playlists" and "Library Data Provider".

**Comment by harryirvine** [comment]
Then you need to install the skin helper service, check this site out: https://kodi.wiki/view/Add-on:Skin_Helper_Service_Widgets

**Comment by freijon** [comment]
That indeed did the trick, thank you!
